### ISSUE TITLE
Improve performance when the Controller is hidden

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#315]
It can cover the whole graph canvas with a Controller and performance is still good.
Sliders are very smooth. 

But sometimes it's slower to move the node's graph, even when the Controllers are hidden.

Could it be possible to improve performance, when all Controllers are hidden ?

**Comment by JorgeR81** [comment]
Currently the best way for me, it's just to remove all Controllers, if I want to make larger changes in the workflow.
And adding them again, once I've made the changes.

If you can't find a better way to improve performance, this could be a workaround:

- When we "hide" the controllers, they actually would be removed. 
- But they layout would be stored, for when we want to show them again.

**Comment by chrisgoringe** [comment]
Rebuilding the controllers is really very fast, so I think the best thing to do will be to destroy them when you hide and rebuild them when you restore.

**Comment by chrisgoringe** [comment]
@JorgeR81 could you turn debugging up to verbose, then hide the controllers and drag the workflow about a bit and see what appears in the javascript console.

**Comment by JorgeR81** [comment]
These lines show up everytime I click and drag to move the workflow, or a node.
There are also a few other lines that appear after them.

And when they show up, the workflow is be stuck for a second.
After 1 or 2 seconds, there are no more messages. 

And when there are no more messages, if I keep dragging ( without click up ), I can move the workflow without problems. 

---

![log](https://github.com/user-attachments/assets/b4afb905-930e-4773-a160-8134e578657b)

**Comment by chrisgoringe** [comment]
That's interesting... can you tell me what those two nodes (26 and 83) are? 

Also, how many controllers do you have, and do they include nodes 26 and 83?

**Comment by JorgeR81** [comment]
These are the `Load Image` nodes.
One for ControlNet and another for Image2Image.
This way I can use different images if I want.
And I can disable them independently on the Controller 


![nodes](https://github.com/user-attachments/assets/718f8f6e-0c7c-4dae-9c38-0469680ab1e5)

---

I have 6 controllers, 1 for each group:

- ControlNet
- Image2Image
- Sampler
- Refiner
- Faced Detailer
- Image Preview

![jpeg](https://github.com/user-attachments/assets/4da36575-b811-4ce9-8d8f-d23acb29929f)

**Comment by chrisgoringe** [comment]
Thanks. The controller seems to be firing about a dozen reload requests, which is surely the reason for the poor performance.

I'll look into it when I'm next at the code!

**Comment by JorgeR81** [comment]
I think I have this same performace issue, when I use `Load Image` nodes, ever since we've got "live preview" in `Preview Image` nodes.

**Comment by chrisgoringe** [comment]
I've made two small updates on dev. One should make the performance much better when the controllers are hidden. The other might improve performance with `Load Image` nodes (let me know how it goes)

**Comment by JorgeR81** [comment]
With controllers hidden, I don't notice any performance issues.
With controllers visible, it's still not perfect, but it's much better. 

---

But now I have a bug:

The controller is not hidden when I click the top bar button.
I also need to click the browser's refresh button, for the Controller to be hidden.

**Comment by JorgeR81** [comment]
> I think I have this same performace issue, when I use Load Image nodes, ever since we've got "live preview" in Preview Image nodes.

> The other might improve performance with Load Image nodes (let me know how it goes)

By the way, is this related to the "live preview" feature ?

I only noticed performance issues once this was implemented. 

If you've changed something in the way the controller is updated to do the "live preview", maybe you can only update that way during generation.

**Comment by chrisgoringe** [comment]
> > I think I have this same performace issue, when I use Load Image nodes, ever since we've got "live preview" in Preview Image nodes.
> 
> > The other might improve performance with Load Image nodes (let me know how it goes)
> 
> By the way, is this related to the "live preview" feature ?
> 
> I only noticed performance issues once this was implemented ( but maybe it was just a coincidence ).
> 
> If you've changed something in the way the controller is updated to do the "live preview", maybe you can only update that way during generation.

Sort of. In order to make live preview work (and also to make the code more isolated, so reducing risk of clashes with other nodes and changes to the core) I changed the way that image changes are detected. The Load Image is a special case because it can *start* with an image (unlike other nodes) and the code I put in for that was checking more than required.

I've just pushed another set of changes to the way updates work which might help performance even more. Could you keep an eye out for anything which *isn't* being updated automatically and post it, and also see how the performance is for you now.

**Comment by JorgeR81** [comment]
This last update seems to have solved all performace issues, even with Controllers visible.

When I move things in the workflow, I have these messages

![log1](https://github.com/user-attachments/assets/763b2353-6a11-4436-bda6-4f545d2bcf40)

---

But I still have this bug:

> The controller is not hidden when I click the top bar button.
> I also need to click the browser's refresh button, for the Controller to be hidden.

**Comment by JorgeR81** [comment]
> The controller is not hidden when I click the top bar button.
> I also need to click the browser's refresh button, for the Controller to be hidden.

This is fixed now.

But now the Controller takes about 2 seconds to show up.
This is a minor issue, but it feels nicer to have the instantaneous response.

With the latest fixes, I see no performance issues even with the Controller visible.

If the toggle "on", speed cannot be improved, maybe "destroying" the hidden Controller could be a performance user setting.

**Comment by chrisgoringe** [comment]
I'm going to close this - remind me if the lag to reappear continues.

**Comment by JorgeR81** [comment]
OK, I'll do that.

But just to clarify, 

The lag happens when the Controller is "rebuild" ( when we toggle visibility "on" ).
