### ISSUE TITLE
Option for image preview nodes not to get upstream updates

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-controller#434]
or to limit how far upstream

In complex workflows, it can be a bit confusing for an image preview to show something that is nothing to do with it (eg a face detailer image preview showing the whole first stage image).

Option one: each image node has a toggle (show upstream progress / don't) defaulting to on
Option two: global limit on how far upstream to look
Option three: each node has limit on how far upstream to look

**Comment by JorgeR81** [comment]
I prefer option one.
But I don't think none of them it's really necessary. 

The current behavior it's perfect for the Controller. 
You can see the current generation for all stages in the same large preview area.

---

This is my setup: 

- I have all the `Image Preview` nodes for each stage, in separate groups ( color coded ).
- And I have a "Final Preview" group, just with an `Image Preview` ( in blue )
_( this is not necessary, but it makes it less confusing, as you mentioned )_

![j2](https://github.com/user-attachments/assets/c784c505-324d-4e33-a347-a5868b4eb188)

---

- All these groups have buttons, in the large preview area.
- The "Final Preview" group it's always selected. I only need to select the other preview groups to compare or save images.
- In the sampler groups, I can see still a small preview, in the Sampler node
- But I can always see the larger version of that, in the "Final Preview" group, as it's being generated. 

![j00](https://github.com/user-attachments/assets/86db8472-244c-4d51-be68-4d43d715b20a)

---

- And when the generation is finished, I have the final image in the large preview area. It works like magic !

![j1](https://github.com/user-attachments/assets/e82f232c-35c9-47b0-9d72-b57b1d638b74)

**Comment by JorgeR81** [comment]
With [ option one ] I could toggle off "show upstream progress", in all preview nodes, except the one in the "Final Preview" group.

The way I have it, I don't see that, anyways, but it could be useful in other configurations.

**Comment by chrisgoringe** [comment]
I think I prefer option one.

My workflow has a number of detailers, including previewers for the detail
areas. I find it unhelpful to see the initial image appearing in the detail
preview node.

But it's not a big issue.

**Comment by JorgeR81** [comment]
Yeah, it if had the `Image Preview`, in each sampler/detailer group, I would want to disable "upstream progress", for them.

I think it could be usefull, in that configuration.

**Comment by chrisgoringe** [comment]
done on dev

**Comment by JorgeR81** [comment]
I just tried the same workflow, in the `main` branch, and it works.

All `Preview Image` nodes have the "live preview", from the first stage.

![main](https://github.com/user-attachments/assets/c83628f3-11fd-4788-8ec8-382aff25f545)

**Comment by chrisgoringe** [comment]
I've just reverted the latest change on dev - can you look now?

**Comment by JorgeR81** [comment]
I've updated `dev` and I don't have this feature. 

But I still have this bug !

So the bug may be created by another change.

**Comment by chrisgoringe** [comment]
Could you file it as a separate bug

**Comment by JorgeR81** [comment]
> Could you file it as a separate bug

OK, done.
