### ISSUE TITLE
[ feature ] better support for rgthree COMBO features   

### ISSUE THREAD

**Issue by JorgeR81** [chrisgoringe/cg-controller#473]
I just realized that the `Power Lora Loader` already supports the extra COMBO features, I asked in here ( https://github.com/chrisgoringe/cg-controller/issues/116 )

- subfolders
- search box

They are working in the Controller, for this node !

![lora](https://github.com/user-attachments/assets/573a67d1-f3b7-4449-8a2f-f9df388c64df)

--- 

The rgthree extension uses the same system in all "Loader" nodes.
It's an option we can enable, to add subfolders.

Instead of creating a new custom COMBO system for the Controller, could it be possible to use the one from rgthree ?

![rs](https://github.com/user-attachments/assets/61eb0181-84a6-4fc3-a588-614fc2f33496)

![rg](https://github.com/user-attachments/assets/3ef386f1-a733-4350-9574-d33fe9209483)

**Comment by chrisgoringe** [comment]
Maybe… although it would require the rgthree pack to be installed…

**Comment by JorgeR81** [comment]
Yeah, it's OK, that's one of the most popular extensions. 

It could be enabled automatically in the Controller, if it's enabled in the rgthree settings.

**Comment by chrisgoringe** [comment]
done on 1.7

**Comment by JorgeR81** [comment]
It's working !

There is only an issue with the Power Lora Loader

If we click multiple times, it shows multiple menus, instead of hiding the previous one.

![lo1](https://github.com/user-attachments/assets/9764e157-e820-4723-aa62-4a5cd31b9695)

**Comment by JorgeR81** [comment]
I noticed that sometimes the custom COMBO box doesn't show the correct selected option.
The first option it's shown as the current selection. 

![zz2](https://github.com/user-attachments/assets/3778c9dc-5f1e-418a-8e76-c484a39fbba0)

---

It has a curious behaviour. 

It will work after we use that COMBO box, in the node's graph ( see images below ).

But after using another COMBO box, in a diferent node ( in the node's graph ), the first combo box will break again. 

![zz1](https://github.com/user-attachments/assets/2f577d1d-7312-4f27-8f0f-d32e60fbf4c4)

![zz3](https://github.com/user-attachments/assets/b2ebca24-70dd-4229-a8e0-eb5569ff6559)

**Comment by JorgeR81** [comment]
There is another issue:

If we zoom in, in the nodes graph, the COMBO box gets larger ( see first image ).
( that's a normal behaviour, I think ). 

The problem is that sometimes it retains that size, in the Controller ( see second image ).
In the controller it could always have the minimum size.

![zz5](https://github.com/user-attachments/assets/a8aa568f-2c3b-43dc-a513-ac3902608f85)

![zz4](https://github.com/user-attachments/assets/68074ae2-efaf-4f25-9944-fe66db97dbbd)

**Comment by chrisgoringe** [comment]
I can't reproduce the size issue.

I believe the other is now fixed.

**Comment by JorgeR81** [comment]
Yes, the first issue is fixed. 

So you can close this issue.

---

About the second issue, ideally I would also like to disable the scaling of combo boxes in the nodes graph. 

I will make a feature request for that, in the frontend repo.

**Comment by chrisgoringe** [comment]
> About the second issue, ideally I would also like to disable the scaling of combo boxes in the nodes graph.
> 
> I will make a feature request for that, in the frontend repo.

I *think* it's done by the custom node pack, actually, not the core frontend.

**Comment by JorgeR81** [comment]
> I think it's done by the custom node pack, actually, not the core frontend.

Do you mean scaling the combo box in the nodes graph ?
That's a native feature. 

I still have this, even with all custom nodes disabled.  I use this cmd, for that:

`--disable-all-custom-nodes`

**Comment by JorgeR81** [comment]
I've created a separete issue for the combox box, scaling, because it's not related specifically to the rgthree combo box ( https://github.com/chrisgoringe/cg-controller/issues/480 )

**Comment by JorgeR81** [comment]
> I can't reproduce the size issue.

Apparently, it only happens in some widgets.

For instance, it happens with `sampler_name`, but not `scheduler`.

Not sure why ?
